# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Segmentasi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 31))
        self.menubar.setObjectName("menubar")
        self.menuSegmentasi = QtWidgets.QMenu(self.menubar)
        self.menuSegmentasi.setObjectName("menuSegmentasi")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegion_Growing = QtWidgets.QAction(MainWindow)
        self.actionRegion_Growing.setObjectName("actionRegion_Growing")
        self.actionK_Means_Clustering = QtWidgets.QAction(MainWindow)
        self.actionK_Means_Clustering.setObjectName("actionK_Means_Clustering")
        self.actionWatershed = QtWidgets.QAction(MainWindow)
        self.actionWatershed.setObjectName("actionWatershed")
        self.actionGlobal_Thresholding = QtWidgets.QAction(MainWindow)
        self.actionGlobal_Thresholding.setObjectName("actionGlobal_Thresholding")
        self.actionAdaptive_Thresholding = QtWidgets.QAction(MainWindow)
        self.actionAdaptive_Thresholding.setObjectName("actionAdaptive_Thresholding")
        self.menuSegmentasi.addAction(self.actionRegion_Growing)
        self.menuSegmentasi.addAction(self.actionK_Means_Clustering)
        self.menuSegmentasi.addAction(self.actionWatershed)
        self.menuSegmentasi.addAction(self.actionGlobal_Thresholding)
        self.menuSegmentasi.addAction(self.actionAdaptive_Thresholding)
        self.menubar.addAction(self.menuSegmentasi.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuSegmentasi.setTitle(_translate("MainWindow", "Segmentasi"))
        self.actionRegion_Growing.setText(_translate("MainWindow", "Region Growing"))
        self.actionK_Means_Clustering.setText(_translate("MainWindow", "K-Means Clustering"))
        self.actionWatershed.setText(_translate("MainWindow", "Watershed"))
        self.actionGlobal_Thresholding.setText(_translate("MainWindow", "Global Thresholding"))
        self.actionAdaptive_Thresholding.setText(_translate("MainWindow", "Adaptive Thresholding"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
